# EET 4501 Applied Machine learning 

## Assignment 7 –   KNN and Linear Regression for Robotic Arm Control


### In this assignment, you will use two different algorithms, linear regression and KNN, to build a inverse kinematic machine learning-based model. The model will obtain the joint angles (q1, ..., q6) of a robot arm based on a given end-effector position (x,y,z).
#### Implementation Steps:
    1) Load the provided dataset.
    2) Get familiar with the data (identify the columns of the joint angles and the space-coordinate).
    3) Split the data in training and testing.
    4) Use linear regression algorithm to train a model for inverse kinematics (to predict the join angles based on the space-coordinates), feel free to use the algorithms provided by libraries such as Sklearn.
    5) Predict over the testing dataset.
    6) Measure the performance of the linear regression algorithm for inverse kinematics using the following metrics: MSE, RMSE, and MAE. This should be done over the unseen dataset (testing). Feel free to use the functions provided by libraries such as Sklearn.
    7) Repeat steps 4) - 6) using KNN algorithm for regression.
    8) Compare both performances and provide a conclusion about which algorithm perform better for this particular task.

Here is a suggested template for this assigment, feel free to modify it to complete the tasks

In [1]:
##Import libraries
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

##Import ML algorithm functions (from sklearn....    )
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsRegressor

##Import the functions to meassure the performance (from sklearn.... )
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [2]:
## loading the dataset using the numpy library
data = np.loadtxt("robot_inverse_kinematics_dataset.csv", skiprows=1, delimiter=',')
print(data.shape)
print(type(data))

(15000, 9)
<class 'numpy.ndarray'>


The dataset has been successfully loaded. It contains 15,000 samples and 9 columns in total. The data is stored in a NumPy ndarray.

In [3]:
## Check the values of data
print(data)

[[-1.51    -0.763    1.85    ... -0.0947   0.15     0.301  ]
 [-2.84     0.52     1.58    ...  0.142   -0.1      0.225  ]
 [-1.23     0.695    1.22    ... -0.0833   0.223    0.206  ]
 ...
 [ 2.62     1.41     1.56    ...  0.131   -0.16     0.362  ]
 [-1.89     1.85     1.51    ...  0.0829  -0.016    0.441  ]
 [ 2.68    -1.79     1.79    ... -0.157   -0.00369  0.254  ]]


In [38]:
# Split the input and output variables

# Split the input  and output  variables
y = data[:, :6]   # First six columns are the joint angles (q1, ..., q6)
X = data[:, 6:]   # Last three columns are the space coordinates (x, y, z)


X[:5], y[:5]  # Display the first 5 rows of the split data to confirm correctness


(array([[-0.0947,  0.15  ,  0.301 ],
        [ 0.142 , -0.1   ,  0.225 ],
        [-0.0833,  0.223 ,  0.206 ],
        [ 0.135 , -0.0314,  0.37  ],
        [-0.056 , -0.229 ,  0.26  ]]),
 array([[-1.51  , -0.763 ,  1.85  , -0.817 ,  0.912 ,  2.32  ],
        [-2.84  ,  0.52  ,  1.58  , -1.27  , -1.39  ,  0.617 ],
        [-1.23  ,  0.695 ,  1.22  , -1.13  ,  0.0343,  6.27  ],
        [-1.99  ,  1.06  ,  1.74  , -1.76  , -1.24  ,  4.76  ],
        [ 1.05  ,  0.836 ,  1.34  , -1.89  ,  0.484 ,  4.38  ]]))

In [33]:
# Print the shapes of input and output variables
print("Shape of input variables (joint angles):", X.shape)
print("Shape of output variables (space co-ordinates):", y.shape)

Shape of input variables (joint angles): (15000, 6)
Shape of output variables (space co-ordinates): (15000, 3)


In [35]:
# Split data into training and validation sets (suggested ration 8:2, suggested random_state=42)

# Using the provided ratio 8:2 and random_state for reproducibility.

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shapes of input and output variables for confirmation
print("Shape of X_train (training set):", X_train.shape)
print("Shape of X_val (validation set):", X_val.shape)
print("Shape of y_train (training set):", y_train.shape)
print("Shape of y_val (validation set):", y_val.shape)



Shape of X_train (training set): (12000, 6)
Shape of X_val (validation set): (3000, 6)
Shape of y_train (training set): (12000, 3)
Shape of y_val (validation set): (3000, 3)


In [36]:
# Normalizing the feature dataset
scaler = MinMaxScaler()


# Fit the scaler on the training input features
scaler.fit(X_train)

# Scale the end-effector position on the training and validation splits
X_train_scaled = scaler.transform(X_train)
X_val_scaled = scaler.transform(X_val)

# Print the first 5 rows of the scaled training and validation input features for confirmation
X_train_scaled[:5], X_val_scaled[:5]



(array([[0.88888889, 0.42526042, 0.5       , 0.57473118, 0.81818182,
         0.64328705],
        [0.89236111, 0.42552083, 0.41428571, 0.71326165, 0.67105263,
         0.57640337],
        [0.61857639, 0.82552083, 0.87142857, 0.55913978, 0.52440191,
         0.00094099],
        [0.75694444, 0.89322917, 0.52857143, 0.5516129 , 0.57105263,
         0.27542683],
        [0.22048611, 0.06510417, 0.27142857, 0.56541219, 0.2722488 ,
         0.85986277]]),
 array([[0.77604167, 0.2109375 , 0.35714286, 0.69892473, 0.63684211,
         0.49677995],
        [0.44201389, 0.17447917, 0.21428571, 0.20967742, 0.49952871,
         0.80094144],
        [0.68923611, 0.60807292, 0.12857143, 0.40806452, 0.41698565,
         0.99203766],
        [0.16319444, 0.6859375 , 0.88571429, 0.13978495, 0.74641148,
         0.2260603 ],
        [0.11805556, 0.97395833, 0.08571429, 0.55806452, 0.83732057,
         0.08831177]]))

In [37]:
# Print shapes of training and validation sets
print('Training set shapes:')
print('X_train:', X_train.shape)
print('y_train:', y_train.shape)

print('\nValidation set shapes:')
print('X_val:', X_val.shape)
print('y_val:', y_val.shape)


Training set shapes:
X_train: (12000, 6)
y_train: (12000, 3)

Validation set shapes:
X_val: (3000, 6)
y_val: (3000, 3)


In [31]:
from sklearn.linear_model import Ridge

# Define the Linear Regression (Ridge) model with different values of alpha
alphas = [0.1, 1.0, 10.0]  # Explore different values for alpha

# Placeholder for model coefficients and intercepts for each alpha
model_details = []

for alpha in alphas:
    # Initialize the Ridge Regression model with the specified alpha
    lr_model = Ridge(alpha=alpha)
    # Fit the model to the training data
    lr_model.fit(X_train_scaled, y_train)
    # Store the model coefficients and intercept for this alpha value
    model_details.append({
        'alpha': alpha,
        'coefficients': lr_model.coef_,
        'intercept': lr_model.intercept_
    })

model_details  # This will output the details of the models for each alpha value



[{'alpha': 0.1,
  'coefficients': array([[ 0.06989146, -2.27235211,  0.12900182],
         [-0.26588581, -0.01809895,  2.86859796],
         [-0.00328011,  0.01960407,  0.28515394],
         [ 0.12168557, -0.10580455, -0.08352363],
         [ 0.08927173,  0.08139835,  0.29345433],
         [ 0.11165273, -0.11051719,  0.00394079]]),
  'intercept': array([ 1.02693479, -1.43576039,  1.40946623,  0.04935932, -0.25033612,
          3.1383193 ])},
 {'alpha': 1.0,
  'coefficients': array([[ 0.06976011, -2.26704879,  0.12885581],
         [-0.2652858 , -0.01812061,  2.86417116],
         [-0.00327559,  0.01955157,  0.28471314],
         [ 0.12140005, -0.10555734, -0.08339339],
         [ 0.08905613,  0.08119988,  0.2929983 ],
         [ 0.11139013, -0.11026089,  0.00393617]]),
  'intercept': array([ 1.02445437, -1.43363576,  1.40972995,  0.04930688, -0.24988331,
          3.13832448])},
 {'alpha': 10.0,
  'coefficients': array([[ 0.0684715 , -2.21534646,  0.12740696],
         [-0.25943348, -0

In [28]:

# Predicting with the lr model on the validation dataset
y_val_pred = lr_model.predict(X_val_scaled)
# Showing the first 5 predictions as an example
y_val_pred[:5]



array([[-0.04159223, -0.73176875,  1.49896148,  0.01947209, -0.092308  ,
         3.12708792],
       [ 0.09937806, -0.96991688,  1.48066724,  0.06484462, -0.08822742,
         3.16488629],
       [ 0.59762342, -0.63965953,  1.5002892 ,  0.03802762, -0.11537243,
         3.14977522],
       [-0.51576202,  0.56480561,  1.63306124, -0.04230211,  0.06082465,
         3.10385429],
       [ 0.10103787,  0.5089433 ,  1.62615038,  0.00892495,  0.05477481,
         3.15412396]])

In [29]:
## Inspect the values prining some samples of joint-angles (y_test) and the predictions generated by the model (predictions - lr) 
# Printing the first 5 samples of actual joint angles from the validation set and their predictions
for actual, predicted in zip(y_val[:5], y_val_pred[:5]):
    print("Actual:", actual)
    print("Predicted:", predicted, "\n")

Actual: [ 1.59  -1.11   1.47   1.11   0.572  3.12 ]
Predicted: [-0.04159223 -0.73176875  1.49896148  0.01947209 -0.092308    3.12708792] 

Actual: [-3.34e-01 -1.25e+00  1.37e+00 -1.62e+00 -1.97e-03  5.03e+00]
Predicted: [ 0.09937806 -0.96991688  1.48066724  0.06484462 -0.08822742  3.16488629] 

Actual: [ 1.09   0.415  1.31  -0.513 -0.347  6.23 ]
Predicted: [ 0.59762342 -0.63965953  1.5002892   0.03802762 -0.11537243  3.14977522] 

Actual: [-1.94   0.714  1.84  -2.01   1.03   1.42 ]
Predicted: [-0.51576202  0.56480561  1.63306124 -0.04230211  0.06082465  3.10385429] 

Actual: [-2.2    1.82   1.28   0.324  1.41   0.555]
Predicted: [0.10103787 0.5089433  1.62615038 0.00892495 0.05477481 3.15412396] 



In [30]:
# Calculate the performance metrics - lr
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Calculate performance metrics for the linear regression model on the validation set
mse_lr = mean_squared_error(y_val, y_val_pred)
mae_lr = mean_absolute_error(y_val, y_val_pred)
r2_lr = r2_score(y_val, y_val_pred)

# Output the performance metrics
mse_lr, mae_lr, r2_lr


(1.8119182407179608, 1.0517663818873861, 0.08031195176837486)

In [23]:
## Define the KNN regressor model, feel free to explore different values for the hyperparameter k
knn_model = KNeighborsRegressor(n_neighbors=5)  # Default value for n_neighbors is 5

# Fit the model to the scaled training data
knn_model.fit(X_train_scaled, y_train)

# Print a message to confirm model fitting
"KNN model fitting complete."




'KNN model fitting complete.'

In [24]:
 
# Predicting with the KNN regressor model on the validation dataset
# Remember, we are using the validation set as our "testing" dataset in this context
y_val_pred_knn = knn_model.predict(X_val_scaled)

# Showing the first 5 predictions as an example
y_val_pred_knn[:5]


array([[-1.4841972, -1.282    ,  1.75     ,  0.1908   , -0.4302   ,
         3.2686   ],
       [ 1.9248   , -0.3698   ,  1.482    , -1.4572   ,  0.41076  ,
         3.762    ],
       [ 0.3232   ,  0.0396   ,  1.35     , -1.0762   ,  0.0645356,
         3.364    ],
       [-0.5583602,  0.8966   ,  1.61     ,  0.1188   , -0.2506   ,
         4.22     ],
       [-0.6514   ,  0.6258   ,  1.528    ,  0.7      ,  0.832    ,
         2.866    ]])

In [25]:
## Inspect the values prining some samples of joint-angles (y_test) and the predictions generated by the model (predictions -knn) 
# Printing the first 5 samples of actual joint angles from the validation set and their predictions
for actual, predicted in zip(y_val[:5], y_val_pred_knn[:5]):
    print("Actual:", actual)
    print("Predicted:", predicted, "\n")


Actual: [ 1.59  -1.11   1.47   1.11   0.572  3.12 ]
Predicted: [-1.4841972 -1.282      1.75       0.1908    -0.4302     3.2686   ] 

Actual: [-3.34e-01 -1.25e+00  1.37e+00 -1.62e+00 -1.97e-03  5.03e+00]
Predicted: [ 1.9248  -0.3698   1.482   -1.4572   0.41076  3.762  ] 

Actual: [ 1.09   0.415  1.31  -0.513 -0.347  6.23 ]
Predicted: [ 0.3232     0.0396     1.35      -1.0762     0.0645356  3.364    ] 

Actual: [-1.94   0.714  1.84  -2.01   1.03   1.42 ]
Predicted: [-0.5583602  0.8966     1.61       0.1188    -0.2506     4.22     ] 

Actual: [-2.2    1.82   1.28   0.324  1.41   0.555]
Predicted: [-0.6514  0.6258  1.528   0.7     0.832   2.866 ] 



In [26]:
# Calculate the performance metrics - knn
# Calculate performance metrics for the KNN regressor model on the validation set
mse_knn = mean_squared_error(y_val, y_val_pred_knn)
mae_knn = mean_absolute_error(y_val, y_val_pred_knn)
r2_knn = r2_score(y_val, y_val_pred_knn)

# Output the performance metrics for KNN
mse_knn, mae_knn, r2_knn


(2.1087274390968656, 1.0858744975099999, 0.009445302092638386)

In [ ]:
# Provide a conclussion of your findings



``Here are some useful sources:``

    https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
    https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
    https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
    https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html
    https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html
    